# Generated by Django 4.2.5 on 2023-10-04 04:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="User Name.", max_length=50)),
                ("gender", models.CharField(max_length=10)),
                ("date_of_birth", models.DateField()),
                ("height", models.IntegerField()),
                ("weight", models.IntegerField()),
                (
                    "country",
                    models.CharField(
                        help_text="The country you currently living.", max_length=50
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="The contact email of the user.", max_length=254
                    ),
                ),
                (
                    "password",
                    models.CharField(help_text="Create a new password.", max_length=50),
                ),
            ],
        ),
    ]
