# Generated by Django 4.2.5 on 2023-10-13 18:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userauth", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
